routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login'); 
});

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','HomeController@login');
Route::get('/log-out', 'HomeController@logout');
Route::get('/home', 'HomeController@dash');

Route::get('/pilih-proyek','HomeController@pilih');
Route::post('/choose','HomeController@chooseproyek');

Route::group(['middleware' => ['role:Komisaris|Manajer|Admin']], function () {
    Route::post('/tambah_proyek','HomeController@tambah_proyek');
    Route::get('/pemesan/get/{kavling}', 'DependencyController@getDataPemesan');
    Route::get('/investor/get/{id}', 'DependencyController@getDataInvestor');
    Route::get('/kode_akun/get/{idakun}', 'DependencyController@getDataTagihan');
});

Route::group(['middleware' => ['permission:create-pemesanan']], function () {
    Route::get('/pemesanan/form', 'PemesananController@form');
    Route::post('/tambah_pesan','PemesananController@tambah_pesan');
    Route::post('/ppjb', 'PemesananController@ppjb');
});

Route::group(['middleware' => ['permission:view-pemesanan']], function () {
    Route::get('/pemesanan', 'PemesananController@index');
    Route::get('/pemesanan/detail/{id}', 'PemesananController@detail');
    Route::post('/ppjb/pdf','PdfController@ppjb');
    Route::get('/pemesanan/detail/ppjb/{ppjb}', 'PemesananController@lihat_ppjb')->name('pemesanan.ppjb');
});

Route::group(['middleware' => ['permission:approval-kuitansi']], function () {
    Route::get('/approval_kuitansi','ApprovalController@kuitansi');
    Route::post('/terimakwt','ApprovalController@terimakwt');
    Route::post('/tolakkwt','ApprovalController@tolakkwt');
    Route::post('/batalkwt','ApprovalController@batalkwt');
    Route::get('/kwitansi/{id}','PdfController@kwitansi');
});

Route::group(['middleware' => ['permission:approval-ppjb']], function () {
    Route::get('/approval_surat','ApprovalController@surat');
    Route::post('/terimappjb','ApprovalController@terimappjb');
    Route::post('/tolakppjb','ApprovalController@tolakppjb');
    Route::post('/batalppjb','ApprovalController@batalppjb');
});

Route::group(['middleware' => ['permission:approval-pembatalan']], function () {
    Route::get('/approval_pembatalan', 'ApprovalController@pembatalan');
    Route::post('/terimapembatalan', 'ApprovalController@terimapembatalan');
    Route::post('/tolakpembatalan', 'ApprovalController@tolakpembatalan');
    Route::post('/batalpembatalan', 'ApprovalController@batalpembatalan');
});

Route::group(['middleware' => ['permission:create-kodeakun']], function () {
    Route::post('/tambah_akun','MasterdataController@tambah_kode');
});

Route::group(['middleware' => ['permission:view-kodeakun']], function () {
    Route::get('/kode-akun','MasterdataController@kodeakun');
});

Route::group(['middleware' => ['permission:create-datakavling']], function () {
    Route::post('/tambah_kavling','MasterdataController@tambah_kavling');
    Route::post('/editharga', 'MasterdataController@edit_harga');
    Route::post('/hapus-data-kavling', 'MasterdataController@hapus_kavling');
});

Route::group(['middleware' => ['permission:view-datakavling']], function () {
    Route::get('/data-kavling','MasterdataController@datakavling');
});

Route::group(['middleware' => ['permission:create-transaksi']], function () {
    Route::get('/penerimaan/form','PenerimaanController@form');
    Route::post('/tambah_transaksi','PenerimaanController@form_post');
    Route::get('/pengeluaran/form','PengeluaranController@form');
    Route::post('/tambah_pengeluaran','PengeluaranController@form_post');
});

Route::group(['middleware' => ['permission:view-transaksi']], function () {
    Route::get('/penerimaan','PenerimaanController@index');
    //Route::get('/penerimaan/detail','PenerimaanController@detail');
    Route::get('/pengeluaran','PengeluaranController@index');
    //Route::get('/pengeluaran/detail','PengeluaranController@detail');
});

Route::group(['middleware' => ['permission:create-pembatalan']], function () {
    Route::get('/pembatalan_pesan/form','PembatalanPesanController@form_batal');
    Route::post('/pembatalan_pesan/form', 'PembatalanPesanController@tambah_batal');
    Route::get('/pembatalan_beli/form','PembatalanBeliController@form_batal');
    Route::post('/pembatalan_beli/form','PembatalanBeliController@tambah_batal');
});

Route::group(['middleware' => ['permission:view-pembatalan']], function () {
    Route::get('/pembatalan_pesan','PembatalanPesanController@index');
    Route::get('/pembatalan_pesan/detail/{id}','PembatalanPesanController@detail');
    Route::get('/pembatalan_beli','PembatalanBeliController@index');
    Route::get('/pembatalan_beli/detail/{id}','PembatalanBeliController@detail');
});

Route::group(['middleware' => ['permission:view-laporan']], function () {
    Route::get('/keuangan/penerimaan','KeuanganController@penerimaan');
    Route::get('/keuangan/penerimaan/detail/{id}','KeuanganController@detail_penerimaan');
    Route::get('/keuangan/pengeluaran','KeuanganController@pengeluaran');
    Route::get('/keuangan/pengeluaran/detail/{id}','KeuanganController@detail_pengeluaran');
    Route::get('/keuangan/laba_rugi','KeuanganController@laba_rugi');
    Route::get('/keuangan/neraca','KeuanganController@neraca');
    Route::get('/keuangan/arus_kas','KeuanganController@arus_kas');
});

Route::group(['middleware' => ['permission:create-feemarketing']], function () {
    Route::post('/tambah_fee','FeeMarketController@tambah_fee');
    Route::post('/bayar_fee','FeeMarketController@bayar_fee');
});

Route::group(['middleware' => ['permission:view-feemarketing']], function () {
    Route::get('/fee-marketing','FeeMarketController@index');
    Route::get('/fee-marketing/history/{id}','FeeMarketController@history');
});

Route::group(['middleware' => ['permission:create-siteplan']], function () {
    Route::post('/tambah_gambar', 'SiteplanController@tambah_img');
});

Route::group(['middleware' => ['permission:view-siteplan']], function () {
    // Route::get('/siteplan', 'SiteplanController@index');
    Route::get('/site-plan', 'SiteplanController@index');
});

Route::group(['middleware' => ['permission:create-investor']], function () {
    Route::get('/investor/form_setor_modal', 'InvestorController@form_setor_modal');
    Route::post('/investor/form_setor_modal', 'InvestorController@setor_modal');
    Route::get('/investor/form_bayar_investor', 'InvestorController@form_bayar_investor');
    Route::post('/investor/form_bayar_investor', 'InvestorController@bayar_investor');
    Route::post('/investor/bukti_perjanjian', 'InvestorController@bukti_perjanjian');
});

Route::group(['middleware' => ['permission:view-investor']], function () {
    Route::get('/investor', 'InvestorController@index');
    Route::get('/investor/detail/{id}', 'InvestorController@detail');
    Route::get('/investor/detail/perjanjian/{perjanjian}', 'InvestorController@lihat_perjanjian')->name('investor.perjanjian');
});

Route::group(['middleware' => ['permission:create-user']], function () {
    Route::post('/user/manage', 'HomeController@manage_user');
    Route::post('/tambah_user','HomeController@tambah_user');
    Route::get('/user/edit/{id}', 'HomeController@edit_user');
    Route::post('/user/edit_user', 'HomeController@save_edit_user');
    Route::post('/user/resetpass', 'HomeController@resetpass');
});

Route::group(['middleware' => ['permission:view-user']], function () {
    Route::get('/user', 'HomeController@lihat_user');
    Route::get('/user/detail/{id}', 'HomeController@detail_user');
    Route::post('/user/ubahpass', 'HomeController@ubahpass');
});

Route::group(['middleware' => ['permission:config-email']], function () {
    Route::get('/konfigurasi_email', 'KonfigurasiController@email');
    Route::get('/konfigurasi_sms', 'KonfigurasiController@sms');
    Route::get('/konfigurasi_surat', 'KonfigurasiController@surat');
    Route::post('/konfigtgt','KonfigurasiController@konfigtenggat');
    Route::post('/konfigpgt','KonfigurasiController@konfigperingatan');
});

Route::group(['middleware' => ['role_or_permission:Komisaris|manage-rolepermission']], function () {
    Route::get('/users/roles/{id}', 'HomeController@roles')->name('users.roles');
    Route::put('/users/roles/{id}', 'HomeController@setRole')->name('users.set_role');
    Route::post('/users/permission', 'HomeController@addPermission')->name('users.add_permission');
    Route::get('/users/role-permission', 'HomeController@rolePermission')->name('users.roles_permission');
    Route::put('/users/permission/{role}', 'HomeController@setRolePermission')->name('users.setRolePermission');
    Route::resource('/role', 'RoleController')->except([
        'create', 'show', 'edit', 'update'
    ]);
});

//Route::get('/pembatalan_beli/form_pengembalian','PembatalanBeliController@form_pengembalian');
//Route::get('/angsuran/form', 'AngsuranController@form');
//Route::get('/angsuran/history', 'AngsuranController@history');
// Route::get('/progress','ProgressController@index');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $roles = Role::orderBy('created_at', 'DESC')->paginate(10);
        return view('role.index', compact('roles'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50'
        ]);

        $role = Role::firstOrCreate(['name' => $request->name]);
        return redirect()->back()->with(['message' => 'Role: ' . $role->name . ' Ditambahkan']);
    }

    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();
        return redirect()->back()->with(['message' => 'Role: ' . $role->name . ' Dihapus']);
    }
}

resources/views/role/index.blade.php
@extends('layouts.base.app')
@section('title', 'Manajemen Role')

@section('sidebar')
    @include('layouts.base.sidebar')
@endsection

@section('header')
    @include('layouts.base.header')
@endsection

@section('content')
<div class="col-12 mb-2 mt-2">
        @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger" role="alert">
                {{ $error }}
            </div>
        @endforeach  
    @endif
    @if(session()->has('message'))
        <div class="alert alert-success" role="alert">
            <strong>Sukses!</strong> {{ session()->get('message') }}
        </div>
    @endif
</div>

<nav class="breadcrumb bg-white push">
    <a class="breadcrumb-item" href="{{url('home')}}">Dashboard</a>
    <span class="breadcrumb-item active">Role</span>
</nav>
<div class="block block-themed block-rounded">
    <div class="block-header bg-gd-lake">
        <h3 class="block-title">Daftar Role</h3>
        <!--<div class="block-options">
            <button type="button" class="btn-block-option">
                <i class="si si-wrench"></i>
            </button>
        </div>-->
    </div>
    <div class="block-content block-content-full">
        <a href="javascript:void(0)" disabled class="btn btn-sm btn-warning mb-3" data-toggle="modal" data-target="#modal-top2"><i class="fa fa-plus mr-2"></i>Tambah Role</a>
        <div class="table-responsive">                            
            <table id="tabel-role" class="stripe table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center d-sm-table-cell" style="width: 10px;">#</th>
                        <th class="d-sm-table-cell">Role</th>
                        <th class="d-sm-table-cell">Guard</th>
                        <th class="d-sm-table-cell">Created At</th>
                        <th class="text-center d-sm-table-cell">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $no = 1;    
                    @endphp
                    @foreach($roles as $role)
                    <tr>
                        <td class="text-center">{{$no++}}</td>
                        <td>{{$role->name}}</td>
                        <td>{{$role->guard_name}}</td>
                        <td>{{$role->created_at}} </td>
                        <td class="text-center">
                            <form action="{{ route('role.destroy', $role->id) }}" method="post" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @empty($role)
                        <tr>
                            <td colspan="5" class="text-center">Tidak ada data</td>
                        </tr>
                    @endempty
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="float-right">
            {!! $roles->links() !!}
        </div>
        <div class="modal fade" id="modal-top2" tabindex="-1" role="dialog" aria-labelledby="modal-top2" aria-hidden="true">
                <div class="modal-dialog modal-dialog-top" role="document">
                <form method="POST" action="{{ route('role.store') }}" enctype="multipart/form-data">
                {{ csrf_field() }}
                    <div class="modal-content">
                        <div class="block block-themed block-transparent mb-0">
                            <div class="block-header bg-primary-dark">
                                <h3 class="block-title">Tambah Role</h3>
                                <div class="block-options">
                                    <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                                        <i class="si si-close"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="block-content">
                                <div class="form-group row">
                                    <label class="col-12" for="name">Nama Role</label>
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Nama Role.." required> 
                                    </div>
                                </div>           
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-alt-secondary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-alt-success">
                                <i class="fa fa-check"></i> Submit
                            </button>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('moreJS')
        <script src="{{asset('codebase/src/assets/js/plugins/datatables/jquery.dataTables.min.js')}}"></script>
        <script src="{{asset('codebase/src/assets/js/plugins/datatables/dataTables.bootstrap4.min.js')}}"></script>
        <script src="{{asset('codebase/src/assets/js/pages/be_tables_datatables.min.js')}}"></script>
        {{-- <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script> --}}
        <script>
            $(document).ready(function(){
                $('#tabel-role').DataTable({
                    "autoWidth": true,
                    "ordering": false,
                });
            });
        </script>
        @endsection